name: Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  deploy-github-pages:
    name: Deploy example page to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install
        env:
          BASE_PATH: '/svelte-jsonschema-form'
        run: |
          npm ci
          touch build/.nojekyll
      - name: Deploy Release
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CONFIG_NAME: github-actions[bot]
          GIT_CONFIG_EMAIL: github-actions[bot]@users.noreply.github.com
